### ISSUE TITLE
Unable to control the tasmota rgb device with mqtt in domoticz

### ISSUE THREAD

**Issue by bean007007007** [stas-demydiuk/domoticz-h801-tasmota-plugin#1]
Hi,
Thanks for creating this great plugin. i've managed to install the plugin and have set the mqtt broker in tasmota and also the server in the plugin in hardware tab of domoticz. i am able to switch the device on and off with mqtt but i am unable to change the collors or brightnes. any tips what i have done wrong with the installation?

**Comment by stas-demydiuk** [comment]
@bean007007007 Have you chosen the proper device type in plugin settings, currently it supports RGB, RGBW, RGBWW or 5 independent dimmers and you need to choose one of them
